set number
set wildmenu
set bg=dark
set hlsearch
set incsearch 
set mouse=a
set wrap!
syntax on 
execute pathogen#infect()
set laststatus=2
set noshowmode
let g:lightline = {
	\ 'colorscheme':'seoul256',
	\ }
