config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
profiles:
  Byakuren:
    dotfiles:
    - f_config
