config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_i3blocks.conf:
    src: i3blocks.conf
    dst: ~/.i3blocks.conf
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_mpdconf:
    src: mpdconf
    dst: ~/.mpdconf
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_sway_config:
    src: config/sway/config
    dst: ~/.config/sway/config
    chmod: '755'
  f_status.toml:
    src: config/sway/status.toml
    dst: ~/.config/sway/status.toml
  f_top.toml:
    src: config/sway/top.toml
    dst: ~/.config/sway/top.toml
  f_dunst_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_rofi_config:
    src: config/rofi/config
    dst: ~/.config/rofi/config
  f_xresources_1:
    src: Xresources
    dst: ~/.Xresources
  f_zshrc_1:
    src: zshrc
    dst: ~/.zshrc
  f_mpdconf_1:
    src: mpdconf
    dst: ~/.mpdconf
profiles:
  Byakuren:
    dotfiles:
    - f_config
    - f_vimrc
    - f_zshrc
    - f_i3blocks.conf
    - f_dunstrc
    - f_config.rasi
    - f_mpdconf
    - f_xresources
  p14s:
    dotfiles:
    - f_sway_config
    - f_status.toml
    - f_top.toml
    - f_dunst_dunstrc
    - f_rofi_config
    - f_xresources_1
    - f_zshrc_1
    - f_mpdconf_1
