##$ hosts: p14s, byakuren2
[theme]
name = "native" #slick
[theme.overrides]
#good_fg = "#FFBF00"
idle_fg= "#FFBF00"
critical_bg = "#FF0000"
critical_fg = "#000000"
warning_bg = "#FF9900"
alternating_tint_bg = "#121212"

[icons]
name = "awesome"
[icons.overrides]
#net_wireless = "" 
time = ""
net_vpn = ""

[[block]]
block = "networkmanager"
interface_name_exclude = ["virbr0", "vnet0"]

[[block]]
block = "net"
interval=2
#signal_strength=true

[[block]]
block = "memory"
icons=true
##$ only: p14s
format_mem="{mem_used}/{mem_total} ({mem_used_percents})"
##$ end
##$ only: byakuren2
format_mem="{Mug}G/{MTg}G ({Mup}%)"
##$ end

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "disk_space"
path = "/home/brod8362/"
alias = "~"
info_type = "available"

[[block]]
block = "cpu"
interval = 2
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
collapsed=false
interval = 10
format = "CPU {max}°C"
##$ only: p14s
chip="k10temp-pci-00c3"
##$ end
##$ only: byakuren2
chip="nct6795-isa-0a20"
inputs = ["CPUTIN", "SYSTIN"]
##$ end
idle=54
info=65
warning=76

##$ only: p14s
[[block]]
block = "custom"
interval=2
command = "echo \"$(cat /sys/class/hwmon/hwmon*/fan1_input) RPM\""
##$ end

#[[block]]
#block = "battery"
#driver = "upower"
#format = "{percentage}% ({time})"
#device="BAT0"

#[[block]]
#block = "battery"
#driver = "upower"
#format = "{percentage}% ({time})"
#device="BAT1"

[[block]]
block = "time"
interval = 60
format = "%Y/%m/%d %R"
