[theme]
theme = "/usr/share/i3status-rust-git/themes/native.toml"
[theme.overrides]
idle_fg = "#FFBF00"
good_fg = "#FFFFFF"

[icons]
icons = "/usr/share/i3status-rust-git/icons/awesome5.toml"

[icons.overrides]
#net_wireless = "" 
time = ""
net_vpn = ""

[[block]]
block = "net"
device = "enp9s0"
format= "$icon $device $ip $speed_down $speed_up"

[[block]]
block = "net"
device = "wg0"
format= "$icon $device $ip $speed_down $speed_up"

[[block]]
block = "memory"
format="$icon $mem_used / $mem_total ($mem_used_percents)"
format_alt="$icon_swap used $swap_used/$swap_total ($swap_used_percents)"

[[block]]
block = "disk_space"
path = "/"
interval = 60
format = "$path $free"

[[block]]
block = "disk_space"
path = "/home/brod8362"
interval = 60
format = "~ $free"

[[block]]
block = "disk_space"
path = "/mnt/ssd"
interval = 60
format = "2 $free"


[[block]]
block = "disk_space"
path = "/mnt/ssd3"
interval = 60
format = "3 $free"

[[block]]
block = "cpu"
interval = 2
format = "$barchart $utilization $frequency"

[[block]]
block = "temperature"
interval = 5
format = "CPU $max"
chip="coretemp-isa-0000"
#inputs = ["CPUTIN", "SYSTIN"]
idle=54
info=65
warning=76


#[[block]]
#block = "battery"
#driver = "upower"
#format = "{percentage}% ({time})"
#device="BAT0"

#[[block]]
#block = "battery"
#driver = "upower"
#format = "{percentage}% ({time})"
#device="BAT1"

[[block]]
block = "time"
interval = 15
format = "$timestamp.datetime(f:'%Y/%m/%d %R')"
