[theme]
theme = "/usr/share/i3status-rust-git/themes/native.toml"
[theme.overrides]
idle_fg = "#FFBF00"
good_fg = "#FFFFFF"

[icons]
icons = "/usr/share/i3status-rust-git/icons/awesome5.toml"

#[[block]]
#block = "focused_window"
#/max_width= 99

[[block]]
block = "custom"
command = "echo \"ssh $(ls ~/.ssh/sockets | wc -l)\""
interval=20

[[block]]
block = "pacman"
interval = 900
format = "$icon $pacman/$aur"
aur_command = "yay -Qua"
critical_updates_regex = "(linux|linux-lts|linux-zen)"

[[block]]
block="weather"
format = "$weather $temp"
service = { name = "openweathermap", api_key = "a5e8a02e6ab96c2954423d4276be801f" , city_id = "4705692", units = "imperial" }
interval=900

[[block]]
block="mpd"
format="$icon $artist - $song [$elapsed/$duration]$flag_r$flag_z$flag_s$flag_c $volume%"
interval = 1 
address = "127.0.0.1:6600"

[[block]]
block = "load"
interval = 1
format = "$icon $1m"


[[block]]
block = "custom"
command = "echo -n \"UPS \" && apcaccess | grep BCHARGE | grep -Eo \"[0-9]+\\.[0]\""
interval = 30


#[[block]]
#block="toggle"
#command_state = "grep LOW_ENERGY /tmp/POWER_PROFILE"
#command_on = "$HOME/bin/prof_power_saving"
#command_off = "$HOME/bin/prof_performance"
#text = "Power Saving"

[[block]]
block="toggle"
command_state= "dunstctl is-paused | grep -o false"
command_on = "dunstctl set-paused false"
command_off = "dunstctl set-paused true"
format="$icon Notifications"


[[block]]
block = "sound"

