[theme]
name = "gruvbox-dark"
[theme.overrides]
good_bg = "#008080"
alternating_tint_bg = "#121212"

[icons]
name = "awesome"

#[[block]]
#block = "focused_window"
#/max_width= 99

[[block]]
block = "pacman"
interval = 900
format = "{pacman}/{aur}"
aur_command = "yay -Qua"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

#[[block]]
#block="weather"
#format = "{weather} {temp}°"
#service = { name = "openweathermap", api_key = "a5e8a02e6ab96c2954423d4276be801f" , city_id = "4705692", units = "imperial" }
#interval=900

[[block]]
block="mpd"
format="{artist} - {title} [{playback_info}]{repeat}{random}{single}{consume} {volume}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
#driver = "upower"
format = "{percentage}% ({time}) {power}W" 
device="BAT0"
#this is the internal battery


[[block]]
block = "battery"
#driver = "upower"
format = "Keyboard {percentage}%" 
device="hid-dc:2c:26:e3:c5:e2-battery"
allow_missing=true
hide_missing=true
#kb battery


[[block]]
block="toggle"
command_state= "dunstctl is-paused | grep -o false"
command_on = "dunstctl set-paused false"
command_off = "dunstctl set-paused true"
text="Notifications"

[[block]]
block="toggle"
command_state = "xinput list-props \"pointer:SynPS/2 Synaptics TouchPad\" | grep \"Device Enabled\" | grep '1$'"
command_on = "xinput enable 'pointer:SynPS/2 Synaptics TouchPad'"
command_off = "xinput disable 'pointer:SynPS/2 Synaptics TouchPad'"
text="Trackpad"

#[[block]]
#block="custom"
#cycle=["speakers","headset"]
#on_click="$HOME/bin/audio_output_swap.sh"

[[block]]
block = "sound"

